// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'adb_box';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String ICON_CAPTURE = 'assets/images/icon_capture.png';
  static const String ICON_CMD = 'assets/images/icon_cmd.png';
  static const String ICON_CURSOR = 'assets/images/icon_cursor.png';
  static const String ICON_DEVICE = 'assets/images/icon_device.png';
  static const String ICON_LOGCAT = 'assets/images/icon_logcat.png';
  static const String ICON_SCREENSHOT = 'assets/images/icon_screenshot.png';
  static const String ICON_SCRIPT = 'assets/images/icon_script.png';
  static const String ICON_SEARCH = 'assets/images/icon_search.png';
  static const String ICON_SETTING = 'assets/images/icon_setting.png';
  static const String ICON_WINDOW_CLOSE = 'assets/images/icon_window_close.png';
  static const String ICON_WINDOW_HIDE = 'assets/images/icon_window_hide.png';
  static const String ICON_WINDOW_MAX = 'assets/images/icon_window_max.png';
  static const String ICON_WINDOW_MIN = 'assets/images/icon_window_min.png';
}
